packages:
  - fixtures/*

overrides:
  '@eslint-community/eslint-utils': ^4.7.0
  '@typescript-eslint/utils': ^8.32.0
  eslint: ^9.26.0
  tsx: ^4.19.4

catalogs:
  dev:
    "eslint-typegen": "^2.1.0"
    "pnpm-workspace-yaml": "^0.3.1"
    "jiti": "^2.4.2"
  cli:
    '@antfu/ni': ^24.1.0
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^6.2.1
  inlined:
    '@antfu/utils': ^9.1.0
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
  prod:
    "@stylistic/eslint-plugin": "^4.2.0"
    "@typescript-eslint/eslint-plugin": "^8.31.1"
    "@typescript-eslint/parser": "^8.31.1"
    "eslint-config-flat-gitignore": "^2.1.0"
    "eslint-flat-config-utils": "^2.0.1"
    "eslint-plugin-antfu": "^3.1.1"
    "eslint-plugin-import-x": "^4.11.0"
    "eslint-plugin-unused-imports": "^4.1.4"
    "local-pkg": "^1.1.1"
    "globals": "^13.12.0"
    "eslint-plugin-unicorn": "^59.0.1"
    "eslint-processor-vue-blocks": "^2.0.0"
    "vue-eslint-parser": "^10.1.3"
    "eslint-plugin-vue": "^10.1.0"
    "eslint-merge-processors": "^2.0.0"
  peer:
    "eslint-plugin-format": "^1.0.1"
    "@prettier/plugin-xml": "^3.4.1"
    "vue": "^3.5.13"

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver

